# Generated by Django 3.2.6 on 2021-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='入学日期')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'unique_together': {('name',)},
            },
        ),
    ]
