# Generated by Django 3.2.6 on 2021-09-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reckondate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('type', models.CharField(max_length=2, verbose_name='类型')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reckondate.personnel', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '调休日志',
                'verbose_name_plural': '调休日志',
            },
        ),
    ]
