# Generated by Django 3.2.6 on 2021-10-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reckondate', '0002_changerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerecord',
            name='type',
            field=models.CharField(default=1, max_length=2, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='start_date',
            field=models.DateField(verbose_name='入学日期'),
        ),
    ]
