# Generated by Django 2.2.5 on 2022-02-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[(1, '动画'), (2, '模型'), (3, '解算'), (4, '灯光'), (5, '制片')], max_length=1, verbose_name='培养方向')),
                ('name', models.OneToOneField(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
    ]
