# Generated by Django 2.2.5 on 2022-02-28 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainees',
            options={'verbose_name': '储备生信息', 'verbose_name_plural': '储备生信息'},
        ),
        migrations.AddField(
            model_name='trainees',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TraineesInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_1', models.IntegerField(verbose_name='⽗⺟⼯作、身体状况')),
                ('target_2', models.IntegerField(verbose_name='兄妹学习、⼯作、⽣活状况')),
                ('target_3', models.IntegerField(verbose_name='家庭整体收⽀情况')),
                ('target_4', models.IntegerField(verbose_name='本⼈身体状况')),
                ('target_5', models.IntegerField(verbose_name='学习习惯、持续时间')),
                ('target_6', models.IntegerField(verbose_name='社会实践获得的收益情况和对过程的感受')),
                ('target_7', models.IntegerField(verbose_name='家庭诱导因素（⽗⺟管教的⼒度、⽗⺟的沟通情况）')),
                ('target_8', models.IntegerField(verbose_name='朋友圈影响因素（与朋友关系的密切程度、朋友的环境因素、朋友对⽣活的态度积极消极的占⽐）')),
                ('target_9', models.IntegerField(verbose_name='⾏业了解程度（了解的⽅式与途径、对其他⾏业了解的状况和程度）')),
                ('target_10', models.IntegerField(verbose_name='性格因素（表达）')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.OneToOneField(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '储备生指标',
                'verbose_name_plural': '储备生指标',
            },
        ),
    ]
