# Generated by Django 2.2.5 on 2022-03-01 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_auto_20220228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineesinterview',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_1',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='⽗⺟⼯作、身体状况'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_10',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='性格因素（表达）'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_2',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='兄妹学习、⼯作、⽣活状况'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_3',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='家庭整体收⽀情况'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_4',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='本⼈身体状况'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_5',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='学习习惯、持续时间'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_6',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='社会实践获得的收益情况和对过程的感受'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_7',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='家庭诱导因素（⽗⺟管教的⼒度、⽗⺟的沟通情况）'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_8',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='朋友圈影响因素（与朋友关系的密切程度、朋友的环境因素、朋友对⽣活的态度积极消极的占⽐）'),
        ),
        migrations.AlterField(
            model_name='traineesinterview',
            name='target_9',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='⾏业了解程度（了解的⽅式与途径、对其他⾏业了解的状况和程度）'),
        ),
    ]
