# Generated by Django 2.2.5 on 2022-03-03 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0005_auto_20220302_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainees',
            options={'verbose_name': '基本信息', 'verbose_name_plural': '基本信息'},
        ),
        migrations.AlterModelOptions(
            name='traineesinterview',
            options={'verbose_name': '面试指标', 'verbose_name_plural': '面试指标'},
        ),
        migrations.AddField(
            model_name='trainees',
            name='address',
            field=models.CharField(default='fdsf', max_length=100, verbose_name='通讯地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='education',
            field=models.CharField(default='fdfd', max_length=40, verbose_name='最高学历'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='education_experience',
            field=models.CharField(default='1', max_length=500, verbose_name='主要教学经历'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='emergency_contact',
            field=models.CharField(default='1', max_length=500, verbose_name='紧急联系人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='entry_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='入训日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='family_member',
            field=models.CharField(default='1', max_length=500, verbose_name='主要家庭成员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default='1', max_length=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='height',
            field=models.IntegerField(default=1, verbose_name='身高'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='id_card',
            field=models.CharField(default=1, max_length=18, verbose_name='身份证号码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='image',
            field=models.ImageField(default=1, upload_to='trainees/%Y-%m-%d/', verbose_name='面部采集'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='lot',
            field=models.CharField(default=1, max_length=20, verbose_name='批次'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='major',
            field=models.CharField(default=1, max_length=40, verbose_name='专业'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='nation',
            field=models.CharField(default=1, max_length=20, verbose_name='民族'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='native',
            field=models.CharField(default=1, max_length=20, verbose_name='籍贯'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='联系电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='politics_status',
            field=models.CharField(default=1, max_length=20, verbose_name='政治面貌'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='trainees',
            name='school',
            field=models.CharField(default=1, max_length=40, verbose_name='毕业院校'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainees',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='体重'),
            preserve_default=False,
        ),
    ]
