# Generated by Django 2.2.5 on 2022-03-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0006_auto_20220303_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainees',
            old_name='entry_time',
            new_name='entry_date',
        ),
    ]
