# Generated by Django 2.2.5 on 2022-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220221_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='user/%Y-%m-%d/', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
