# Generated by Django 2.2.5 on 2022-03-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_time', models.DateTimeField(verbose_name='上班排班时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='上班打卡时间')),
                ('shift_end_time', models.DateTimeField(verbose_name='下班排班时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='下班打卡时间')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '考勤组',
                'verbose_name_plural': '考勤组',
            },
        ),
        migrations.CreateModel(
            name='AttendanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='名称')),
                ('shift', models.CharField(max_length=200, verbose_name='班次')),
                ('personnel', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='考勤人员')),
            ],
            options={
                'verbose_name': '考勤组',
                'verbose_name_plural': '考勤组',
            },
        ),
    ]
