# Generated by Django 2.2.5 on 2022-03-10 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancegroup',
            name='personnel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='考勤人员'),
        ),
    ]
