# Generated by Django 2.1.4 on 2019-10-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_auto_20191011_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallyrecord',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit_price',
            field=models.FloatField(default=0, verbose_name='单价'),
        ),
    ]
