# Generated by Django 2.1.4 on 2019-10-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_auto_20191011_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='payee',
            options={'verbose_name': '收款单位', 'verbose_name_plural': '收款单位'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterModelOptions(
            name='tallyrecord',
            options={'verbose_name': '记账记录', 'verbose_name_plural': '记账记录'},
        ),
    ]
