# Generated by Django 2.1.4 on 2019-10-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0006_auto_20191016_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('subtitle', models.CharField(max_length=20, verbose_name='副标题')),
                ('logo_image', models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/logo/%Y/%m', verbose_name='logo')),
                ('head', models.CharField(max_length=20, verbose_name='左上标题')),
                ('remark', models.TextField(max_length=500, verbose_name='备注')),
                ('bottom1', models.CharField(max_length=20, verbose_name='底部标题1')),
                ('bottom2', models.CharField(max_length=20, verbose_name='底部标题2')),
                ('bottom3', models.CharField(max_length=20, verbose_name='底部标题3')),
                ('bottom4', models.CharField(max_length=20, verbose_name='底部标题4')),
                ('bottom5', models.CharField(max_length=20, verbose_name='底部标题5')),
                ('right', models.CharField(max_length=20, verbose_name='右侧标题')),
            ],
            options={
                'verbose_name': '打印设置',
                'verbose_name_plural': '打印设置',
            },
        ),
    ]
