# Generated by Django 3.0.6 on 2020-06-05 02:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tally', '0007_printset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'verbose_name': '账单明细',
                'verbose_name_plural': '账单明细',
            },
        ),
        migrations.CreateModel(
            name='ClientPaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('0', '充值'), ('1', '消费')], max_length=2, verbose_name='充值类型')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '充值消费记录',
                'verbose_name_plural': '充值消费记录',
            },
        ),
        migrations.AlterModelOptions(
            name='tallyrecord',
            options={'verbose_name': '账单', 'verbose_name_plural': '账单'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit_price',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='has_tray',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='operating_expenses',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='payee_name',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='returned_money',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='transport_expenses',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='unloading_expenses',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='use_date',
        ),
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.FloatField(default=0, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='client',
            name='car_number',
            field=models.CharField(default=1, max_length=10, verbose_name='车牌号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, verbose_name='销售价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=1, verbose_name='进价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='产品介绍'),
        ),
        migrations.AddField(
            model_name='product',
            name='repertory',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='tallyrecord',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='tallyrecord',
            name='tally_type',
            field=models.CharField(choices=[('in', '进货'), ('out', '出货')], default=1, max_length=3, verbose_name='进出货'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品编号'),
        ),
        migrations.DeleteModel(
            name='Payee',
        ),
        migrations.AddField(
            model_name='clientpaymentrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Client', verbose_name='会员'),
        ),
        migrations.AddField(
            model_name='clientpaymentrecord',
            name='handlers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tally.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='tally_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.TallyRecord', verbose_name='账单'),
        ),
    ]
