# Generated by Django 3.0.6 on 2020-06-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0008_auto_20200605_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tally.Product', verbose_name='产品'),
        ),
    ]
