# Generated by Django 3.0.6 on 2020-06-05 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tally', '0009_auto_20200605_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyrecord',
            name='handlers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
