# Generated by Django 3.0.6 on 2020-06-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_tallyrecord_handlers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpaymentrecord',
            old_name='handlers',
            new_name='handler',
        ),
        migrations.RenameField(
            model_name='tallyrecord',
            old_name='handlers',
            new_name='handler',
        ),
    ]
