# Generated by Django 3.0.6 on 2020-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_auto_20200605_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account',
        ),
        migrations.AddField(
            model_name='clientpaymentrecord',
            name='money',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
    ]
