# Generated by Django 3.0.6 on 2020-06-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_auto_20200605_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='repertory',
        ),
    ]
