# Generated by Django 3.0.6 on 2020-06-11 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0013_remove_product_repertory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
    ]
