# Generated by Django 3.0.6 on 2020-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_client_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/product_default.jpg', null=True, upload_to='image/product/%Y/%m', verbose_name='产品图'),
        ),
    ]
