# Generated by Django 3.0.6 on 2020-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/car_photo/%Y/%m', verbose_name='车牌相片')),
            ],
            options={
                'verbose_name': '车牌相片',
                'verbose_name_plural': '车牌相片',
            },
        ),
    ]
