# Generated by Django 3.0.6 on 2020-06-15 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0016_uploadphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentrecord',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
