# Generated by Django 3.0.6 on 2020-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0017_clientpaymentrecord_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='top',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
