# Generated by Django 3.0.6 on 2020-06-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0018_client_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='top',
        ),
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
