# Generated by Django 3.2.6 on 2021-08-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tally', '0020_auto_20200616_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('action', models.CharField(choices=[('nan', '男'), ('nv', '女')], max_length=3, verbose_name='操作类型')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='操作内容')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='编号')),
                ('board', models.CharField(max_length=50, verbose_name='主板')),
                ('cpu', models.CharField(max_length=50, verbose_name='cpu')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('price', models.FloatField(default=0, verbose_name='价值')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='编号')),
                ('type', models.CharField(max_length=11, verbose_name='型号')),
                ('size', models.CharField(max_length=10, verbose_name='尺寸')),
                ('price', models.FloatField(default=0, verbose_name='价值')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '显示器',
                'verbose_name_plural': '显示器',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('nan', '男'), ('nv', '女')], max_length=3, verbose_name='性别')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('job', models.CharField(max_length=20, verbose_name='岗位')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('computer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tally.computer', verbose_name='主机')),
                ('monitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tally.monitor', verbose_name='显示器')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='tally_record',
        ),
        migrations.RemoveField(
            model_name='clientpaymentrecord',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpaymentrecord',
            name='handler',
        ),
        migrations.DeleteModel(
            name='PrintSet',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='tallyrecord',
            name='handler',
        ),
        migrations.DeleteModel(
            name='UploadPhoto',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientPaymentRecord',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TallyRecord',
        ),
    ]
