# Generated by Django 3.2.6 on 2021-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0021_auto_20210804_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='memory',
            new_name='ram',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='board',
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu',
            field=models.CharField(default='efefe', max_length=50, verbose_name='显卡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd',
            field=models.CharField(default='fefefe', max_length=50, verbose_name='硬盘'),
            preserve_default=False,
        ),
    ]
