# Generated by Django 3.2.6 on 2021-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0023_auto_20210818_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mac',
            field=models.CharField(default=-143, max_length=17, verbose_name='mac'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together={('number', 'mac')},
        ),
        migrations.AlterUniqueTogether(
            name='monitor',
            unique_together={('number',)},
        ),
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('name',)},
        ),
    ]
