# Generated by Django 3.2.6 on 2021-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0027_auto_20210825_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrecord',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='申请日期'),
        ),
    ]
